[bindings.kotlin]
package_name = "org.vaultkern.core"
cdylib_name = "vaultkern_uniffi"

[bindings.swift]
module_name = "VaultKernCore"
ffi_module_name = "VaultKernCoreFFI"
cdylib_name = "vaultkern_uniffi"
